config/routes.rb
Rails.application.routes.draw do
  resources :visits
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'session#login'
    get 'session/login'
    post 'session/create'
    get 'session/logout'
    get 'users/new_doctor'
    post 'users/create_doctor'
    resources :users
    resources :data
    resources :visit
    get 'visits/new_block'
    post 'visits/create_block'
    get 'visits/filter'
    get 'main/select'
    get 'main/analyze'
    get 'main/filter'
    get 'main/view_all'
    get 'main/view_date'
    get 'main/view_vis'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/main_controller.rb
# frozen_string_literal: true

DOCTOR = 'doctor'
class MainController < ApplicationController
  include MainHelper
  before_action :parse_params, only: %i[view_all]
  before_action :parse_params1, only: :view_vis
  before_action :check_login, only: %i[select view_all view_date view_vis]

  def select
    if @current_user.role==DOCTOR
      doctor_visits = Visit.all.select do |record|
        record.user!= "" && record.doctor == current_user.username
      end.select{|record| record.user!=nil}.pluck(:user).uniq
      @patients=doctor_visits.map do |record|
        record=User.find_by_username(record).surname+" "+User.find_by_username(record).name+" "+User.find_by_username(record).patr
      end
    end
  end

  def view_all
    if @act == 'view_all'
      p 'view_all'
      redirect_to data_path
    elsif @act == 'find_date'
      p 'find_date'
      @data = Datum.all.select do |record|
        record.username == @current_user.username && record.data.to_date.strftime('%Y-%m-%d') == @date
      end.sort_by(&:data).reverse!
    elsif @act == 'find_pat' && @current_user.role == DOCTOR
      if @name != '' && @surname != '' && @patr != ''
        p 'find_pat'
        user = User.find_by_name_and_surname_and_patr(@name, @surname, @patr)
        if !user.nil?
          @@user_for_analysis=user
          @data = Datum.all.select { |record| record.username == user.username }.sort_by(&:data).reverse!
          @date = "#{user.surname} #{user.name} #{user.patr}"
          if !@data.nil?
            @data_chart_temp={}
            @data.map do |datum|
             @data_chart_temp[datum.data-10800]=datum.temp
            end
            @data_chart_h_pres={}
            @data.map do |datum|
              @data_chart_h_pres[datum.data-10800]=datum.h_pres
            end
            @data_chart_l_pres={}
            @data.map do |datum|
             @data_chart_l_pres[datum.data-10800]=datum.l_pres
            end
            @data_chart_pulse={}
            @data.map do |datum|
             @data_chart_pulse[datum.data-10800]=datum.pulse
            end
            @data_chart_satur={}
            @data.map do |datum|
             @data_chart_satur[datum.data-10800]=datum.satur
            end
          else
            @data_chart={}
            @data_chart_h_pres={}
            @data_chart_l_pres={}
            @analysis="За последнюю неделю записей в дневнике здоровья нет"
          end
        else
          redirect_to main_select_path, notice: t('session.login.user_not_found') end
      else
        redirect_to main_select_path, notice: t('main.select.enter_all_info')
      end
    else
      p 'new_record'
      redirect_to new_datum_path
    end
  end

  def view_vis
    user = User.find_by_username(@current_user.username)
    @date = "#{user.surname} #{user.name} #{user.patr}"
    if @act1 == 'view_last' && @current_user.role!=DOCTOR
      p 'view_last'
      #if @date_from != '' && @date_to!= ''
        @data = Visit.all.select do |record| record.user == @current_user.username && record.date.to_date <= Time.now end.sort_by(&:date).reverse
      #else
        ##redirect_to main_select_path, notice: t('main.select.enter_all_info')
      #end 
    elsif @act1 == 'view_last' && @current_user.role==DOCTOR
      if @name != '' && @surname != '' && @patr != ''
        user = User.find_by_name_and_surname_and_patr(@name, @surname, @patr)
        if !user.nil?
          @data = Visit.all.select { |record| record.user == user.username && record.date.to_date <= Time.now }.sort_by(&:date).reverse!
          @date = "#{user.surname} #{user.name} #{user.patr}"
        else
          redirect_to main_select_path, notice: t('session.login.user_not_found')
        end
      else
        redirect_to main_select_path, notice: t('main.select.enter_all_info')
      end
    elsif @act1 == 'view_fut' && @current_user.role!=DOCTOR
      p 'view_fut'
      @data = Visit.all.select do |record| record.user == @current_user.username && record.date >= Time.now end.sort_by(&:date)
    elsif @act1 == 'view_fut' && @current_user.role==DOCTOR
      p 'view_fut'
      redirect_to visits_path
    elsif @act1 == 'add_vis'
      p 'add_vis'
      redirect_to visits_path
    end
  end

  def view_date
    @actual_record = Datum.all.select do |record|
      record.username == @current_user.username
    end.sort_by(&:data).reverse!.take(1)
    p @actual_record
    respond_to do |f|
      f.html
      f.json do
        render json: { actual_record: @actual_record }
      end
    end
  end

  def filter
    render json: { data: @data}
  end

  def analyze
    @number_days = params[:number_days]
    p @@user_for_analysis.name
    data_week=Datum.all.select{|record| record.username == @@user_for_analysis.username && record.data<=Time.now+10800 &&record.data>=Time.now-(86400*@number_days.to_i)}
    if data_week!=[]
      temp_max=data_week.max_by{|temp| temp[:temp]}.temp
      temp_max_date=data_week.max_by{|temp| temp[:temp]}.data.strftime("%Y-%m-%d %H:%M")
      temp_min=data_week.min_by{|temp| temp[:temp]}.temp
      temp_min_date=data_week.min_by{|temp| temp[:temp]}.data.strftime("%Y-%m-%d %H:%M")
      h_pres_max=data_week.max_by{|pres| pres[:h_pres]}.h_pres
      h_pres_max_date=data_week.max_by{|pres| pres[:h_pres]}.data.strftime("%Y-%m-%d %H:%M")
      h_pres_min=data_week.min_by{|pres| pres[:h_pres]}.h_pres
      h_pres_min_date=data_week.min_by{|pres| pres[:h_pres]}.data.strftime("%Y-%m-%d %H:%M")
      l_pres_max=data_week.max_by{|pres| pres[:l_pres]}.l_pres
      l_pres_max_date=data_week.max_by{|pres| pres[:l_pres]}.data.strftime("%Y-%m-%d %H:%M")
      l_pres_min=data_week.min_by{|pres| pres[:l_pres]}.l_pres
      l_pres_min_date=data_week.min_by{|pres| pres[:l_pres]}.data.strftime("%Y-%m-%d %H:%M")
      pulse_max=data_week.max_by{|temp| temp[:pulse]}.pulse
      pulse_max_date=data_week.max_by{|temp| temp[:pulse]}.data.strftime("%Y-%m-%d %H:%M")
      pulse_min=data_week.min_by{|temp| temp[:pulse]}.pulse
      pulse_min_date=data_week.min_by{|temp| temp[:pulse]}.data.strftime("%Y-%m-%d %H:%M")
      satur_select=data_week.select{|record| record.satur<=95}
      @max_temp = "Максимальное значение температуры: #{temp_max}С (дата: #{temp_max_date})"
      @min_temp = "Минимальное значение температуры: #{temp_min}С (дата: #{temp_min_date})"
      @h_pres = "Систолическое АД изменялось в пределах: #{h_pres_min} мм рт.ст. (дата: #{h_pres_min_date}) - #{h_pres_max} мм рт.ст. (дата: #{h_pres_max_date})"
      @l_pres = "Диастолическое АД изменялось в пределах: #{l_pres_min} мм рт.ст. (дата: #{l_pres_min_date}) - #{l_pres_max} мм рт.ст. (дата: #{l_pres_max_date})"
      @pulse = "ЧСС изменялась в пределах: #{pulse_min} ударов/мин (дата: #{pulse_min_date}) - #{pulse_max} ударов/мин (дата: #{pulse_max_date})"
      if !(satur_select==[])
       @satur = "Сатурация была ниже нормы (<=95%): "
       satur_select.each do |record|
        @satur = @satur + record.satur.to_s + "% (дата: " + record.data.strftime("%Y-%m-%d %H:%M") + ")  "
       end
     else @satur = "Сатурация была в норме (>95%)"
     end
     @data_chart_temp={}
     data_week.map do |datum|
        @data_chart_temp[datum.data-10800]=datum.temp
     end
            @data_chart_h_pres={}
            data_week.map do |datum|
              @data_chart_h_pres[datum.data-10800]=datum.h_pres
            end
            @data_chart_l_pres={}
            data_week.map do |datum|
             @data_chart_l_pres[datum.data-10800]=datum.l_pres
            end
            @data_chart_pulse={}
            data_week.map do |datum|
             @data_chart_pulse[datum.data-10800]=datum.pulse
            end
            @data_chart_satur={}
            data_week.map do |datum|
             @data_chart_satur[datum.data-10800]=datum.satur
            end
   else 
    @analysis="Записей в дневнике здоровья за выбранный период нет"
    @data_chart_temp={}
    @data_chart_h_pres={}
    @data_chart_l_pres={}
    @data_chart_satur={}
    @data_chart_satur={}
   end
   render json: { data_chart_l_pres: @data_chart_l_pres, data_chart_pulse: @data_chart_pulse, data_chart_satur: @data_chart_satur, data_chart_temp: @data_chart_temp, data_chart_h_pres: @data_chart_h_pres, max_temp: @max_temp, min_temp: @min_temp, h_pres: @h_pres, l_pres: @l_pres, pulse: @pulse, satur: @satur, analysis: @analysis, data_chart_temp: @data_chart_temp }
  end

  private

  def parse_params
    @date = params[:date]
    @act = params[:act]
    #@date_from = params[:date_from]
    #@date_to = params[:date_to]
    @name = params[:name]
    @surname = params[:surname]
    @patr = params[:patr]
  end
  
  def parse_params1
    @date = ""
    @act1 = params[:act1]
    ##@date_from = params[:date_from]
    ##@date_to = params[:date_to]
    @name = params[:name]
    @surname = params[:surname]
    @patr = params[:patr]
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/select.html.erb
<div class="center jumbotron">
<h2><%= t('.welcome') %> <%=@current_user.surname %> <%=@current_user.name %> <%=@current_user.patr %></h2>
<div class="error" ><%= notice %></div>
<% if @current_user.role !='doctor'  && @current_user.username !='admin'%><%= form_tag  url_for(controller: :main, action: :view_all), method: 'get' do %>

  <% if Visit.all.select {|record| record.user == @current_user.username && record.date.to_date >= Time.now}.sort_by(&:date)[0] != nil %>  
  <div class="alert alert-success" role="alert">
  <%= t('.near_date') %>
       <%=Visit.all.select do |record| record.user == @current_user.username && record.date >= Time.now end.sort_by(&:date)[0].date.strftime("%Y-%m-%d %H:%M") %> <br>
        Врач: <%= User.find_by_username(Visit.all.select do |record| record.user == @current_user.username && record.date >= Time.now end.sort_by(&:date)[0].doctor).surname %>
          <%= User.find_by_username(Visit.all.select do |record| record.user == @current_user.username && record.date >= Time.now end.sort_by(&:date)[0].doctor).name %>
            <%= User.find_by_username(Visit.all.select do |record| record.user == @current_user.username && record.date >= Time.now end.sort_by(&:date)[0].doctor).patr %> 
    </div>
    <%end%>

  
    <fieldset class="form-group">

      <legend><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-clipboard2-pulse" viewBox="0 0 16 16">
      <path d="M9.5 0a.5.5 0 0 1 .5.5.5.5 0 0 0 .5.5.5.5 0 0 1 .5.5V2a.5.5 0 0 1-.5.5h-5A.5.5 0 0 1 5 2v-.5a.5.5 0 0 1 .5-.5.5.5 0 0 0 .5-.5.5.5 0 0 1 .5-.5h3Z"/>
      <path d="M3 2.5a.5.5 0 0 1 .5-.5H4a.5.5 0 0 0 0-1h-.5A1.5 1.5 0 0 0 2 2.5v12A1.5 1.5 0 0 0 3.5 16h9a1.5 1.5 0 0 0 1.5-1.5v-12A1.5 1.5 0 0 0 12.5 1H12a.5.5 0 0 0 0 1h.5a.5.5 0 0 1 .5.5v12a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5v-12Z"/>
      <path d="M9.979 5.356a.5.5 0 0 0-.968.04L7.92 10.49l-.94-3.135a.5.5 0 0 0-.926-.08L4.69 10H4.5a.5.5 0 0 0 0 1H5a.5.5 0 0 0 .447-.276l.936-1.873 1.138 3.793a.5.5 0 0 0 .968-.04L9.58 7.51l.94 3.135A.5.5 0 0 0 11 11h.5a.5.5 0 0 0 0-1h-.128L9.979 5.356Z"/>
    </svg>Дневник здоровья</legend>

      <div class="form-check">
        <label class="form-check-label">
          <input type="radio" class="form-check-input" name="act" value="view_all" id="view_all" checked>
          <%= t('.show_all') %>
        </label>
      </div>
      
      <div class="form-check">
        <label class="form-check-label">
          <input type="radio" class="form-check-input" name="act" value="find_date" id="find_date">
          <%= t('.view_date') %> <input type="date" id="date" name="date" value="2024-01-10" />
        </label>
      </div>

      <div class="form-check">
        <label class="form-check-label">
          <input type="radio" class="form-check-input" name="act" value="add_record" id="add_record">
          <%= t('.add') %>
        </label>
      </div>

    </fieldset>

    <%= submit_tag(t('.choose')) %> 
    <%end%>
    
    <%= form_tag  url_for(controller: :main, action: :view_vis), method: 'get' do %>

    <fieldset class="form-group">

      <legend><svg xmlns="http://www.w3.org/2000/svg" width="38" height="30" fill="currentColor" class="bi bi-hospital" viewBox="0 0 16 16">
      <path d="M8.5 5.034v1.1l.953-.55.5.867L9 7l.953.55-.5.866-.953-.55v1.1h-1v-1.1l-.953.55-.5-.866L7 7l-.953-.55.5-.866.953.55v-1.1h1ZM13.25 9a.25.25 0 0 0-.25.25v.5c0 .138.112.25.25.25h.5a.25.25 0 0 0 .25-.25v-.5a.25.25 0 0 0-.25-.25h-.5ZM13 11.25a.25.25 0 0 1 .25-.25h.5a.25.25 0 0 1 .25.25v.5a.25.25 0 0 1-.25.25h-.5a.25.25 0 0 1-.25-.25v-.5Zm.25 1.75a.25.25 0 0 0-.25.25v.5c0 .138.112.25.25.25h.5a.25.25 0 0 0 .25-.25v-.5a.25.25 0 0 0-.25-.25h-.5Zm-11-4a.25.25 0 0 0-.25.25v.5c0 .138.112.25.25.25h.5A.25.25 0 0 0 3 9.75v-.5A.25.25 0 0 0 2.75 9h-.5Zm0 2a.25.25 0 0 0-.25.25v.5c0 .138.112.25.25.25h.5a.25.25 0 0 0 .25-.25v-.5a.25.25 0 0 0-.25-.25h-.5ZM2 13.25a.25.25 0 0 1 .25-.25h.5a.25.25 0 0 1 .25.25v.5a.25.25 0 0 1-.25.25h-.5a.25.25 0 0 1-.25-.25v-.5Z"/>
      <path d="M5 1a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v1a1 1 0 0 1 1 1v4h3a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V8a1 1 0 0 1 1-1h3V3a1 1 0 0 1 1-1V1Zm2 14h2v-3H7v3Zm3 0h1V3H5v12h1v-3a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3Zm0-14H6v1h4V1Zm2 7v7h3V8h-3Zm-8 7V8H1v7h3Z"/>
    </svg>Приёмы врача</legend>

      <div class="form-check">
        <label class="form-check-label">
          <input type="radio" class="form-check-input" name="act1" value="view_last" id="view_vis" checked>
          Посмотреть историю приёмов 
        </label>
      </div>
      
      <div class="form-check">
        <label class="form-check-label">
          <input type="radio" class="form-check-input" name="act1" value="view_fut" id="view_fut">
          Посмотреть имеющиеся записи на приём
        </label>
      </div>

      <div class="form-check">
        <label class="form-check-label">
          <input type="radio" class="form-check-input" name="act1" value="add_vis" id="add_vis">
          <%= t('.add_vis') %>
        </label>
      </div>

    </fieldset>

    <%= submit_tag(t('.choose')) %> 
<% end %>
</br>

  

<% elsif @current_user.role =='doctor' %>
<p id="hidden"><%=@patients %></p>
  <%= form_tag  url_for(controller: :main, action: :view_all), method: 'get' do %>

    <fieldset class="form-group">

      <legend><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-clipboard2-pulse" viewBox="0 0 16 16">
      <path d="M9.5 0a.5.5 0 0 1 .5.5.5.5 0 0 0 .5.5.5.5 0 0 1 .5.5V2a.5.5 0 0 1-.5.5h-5A.5.5 0 0 1 5 2v-.5a.5.5 0 0 1 .5-.5.5.5 0 0 0 .5-.5.5.5 0 0 1 .5-.5h3Z"/>
      <path d="M3 2.5a.5.5 0 0 1 .5-.5H4a.5.5 0 0 0 0-1h-.5A1.5 1.5 0 0 0 2 2.5v12A1.5 1.5 0 0 0 3.5 16h9a1.5 1.5 0 0 0 1.5-1.5v-12A1.5 1.5 0 0 0 12.5 1H12a.5.5 0 0 0 0 1h.5a.5.5 0 0 1 .5.5v12a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5v-12Z"/>
      <path d="M9.979 5.356a.5.5 0 0 0-.968.04L7.92 10.49l-.94-3.135a.5.5 0 0 0-.926-.08L4.69 10H4.5a.5.5 0 0 0 0 1H5a.5.5 0 0 0 .447-.276l.936-1.873 1.138 3.793a.5.5 0 0 0 .968-.04L9.58 7.51l.94 3.135A.5.5 0 0 0 11 11h.5a.5.5 0 0 0 0-1h-.128L9.979 5.356Z"/>
    </svg>Дневник здоровья</legend>

      <div class="form-check">
        <label class="form-check-label">
          <input type="radio" class="form-check-input" name="act" value="view_all" id="view_all" checked>
          <%= t('.show_all') %>
        </label>
      </div>
      
      <div class="form-check">
        <label class="form-check-label">
          <input type="radio" class="form-check-input" name="act" value="find_pat" id="find_pat">
          <%= t('.show_pat') %>
        </label><br>
        <%= t('.surname') %> <input type="text_field" id="surname" name="surname" remote="true"/>
        <%= t('.name') %> <input type="text_field" id="name" name="name" remote="true"/>
        <%= t('.patronymic') %> <input type="text_field" id="patr" name="patr" remote="true"/>
      </div>

    </fieldset>

    <%= submit_tag(t('.choose')) %> <%end%>

    <%= form_tag  url_for(controller: :main, action: :view_vis), method: 'get' do %>

      <fieldset class="form-group">
  
        <legend><svg xmlns="http://www.w3.org/2000/svg" width="38" height="30" fill="currentColor" class="bi bi-hospital" viewBox="0 0 16 16">
        <path d="M8.5 5.034v1.1l.953-.55.5.867L9 7l.953.55-.5.866-.953-.55v1.1h-1v-1.1l-.953.55-.5-.866L7 7l-.953-.55.5-.866.953.55v-1.1h1ZM13.25 9a.25.25 0 0 0-.25.25v.5c0 .138.112.25.25.25h.5a.25.25 0 0 0 .25-.25v-.5a.25.25 0 0 0-.25-.25h-.5ZM13 11.25a.25.25 0 0 1 .25-.25h.5a.25.25 0 0 1 .25.25v.5a.25.25 0 0 1-.25.25h-.5a.25.25 0 0 1-.25-.25v-.5Zm.25 1.75a.25.25 0 0 0-.25.25v.5c0 .138.112.25.25.25h.5a.25.25 0 0 0 .25-.25v-.5a.25.25 0 0 0-.25-.25h-.5Zm-11-4a.25.25 0 0 0-.25.25v.5c0 .138.112.25.25.25h.5A.25.25 0 0 0 3 9.75v-.5A.25.25 0 0 0 2.75 9h-.5Zm0 2a.25.25 0 0 0-.25.25v.5c0 .138.112.25.25.25h.5a.25.25 0 0 0 .25-.25v-.5a.25.25 0 0 0-.25-.25h-.5ZM2 13.25a.25.25 0 0 1 .25-.25h.5a.25.25 0 0 1 .25.25v.5a.25.25 0 0 1-.25.25h-.5a.25.25 0 0 1-.25-.25v-.5Z"/>
        <path d="M5 1a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v1a1 1 0 0 1 1 1v4h3a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V8a1 1 0 0 1 1-1h3V3a1 1 0 0 1 1-1V1Zm2 14h2v-3H7v3Zm3 0h1V3H5v12h1v-3a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3Zm0-14H6v1h4V1Zm2 7v7h3V8h-3Zm-8 7V8H1v7h3Z"/>
      </svg>Приёмы врача</legend>
  
        <div class="form-check">
          <label class="form-check-label">
            <input type="radio" class="form-check-input" name="act1" value="view_last" id="view_vis" checked>
            <%= t('.view_last_1') %>
          </label><br>
          <%= t('.surname') %> <input type="text_field" id="surname1" name="surname" remote="true"/>
          <%= t('.name') %> <input type="text_field" id="name1" name="name" remote="true"/>
          <%= t('.patronymic') %> <input type="text_field" id="patr1" name="patr" remote="true"/>
        </div>
        
        <div class="form-check">
          <label class="form-check-label">
            <input type="radio" class="form-check-input" name="act1" value="view_fut" id="view_fut">
            Посмотреть имеющиеся записи на приём
          </label>
        </div>
  
      </fieldset>
  
      <%= submit_tag(t('.choose')) %> 
  <% end %>
<%elsif @current_user.username =='admin'%>  
<button><%= link_to "Зарегистрировать профиль врача", users_new_doctor_path %></button>
<button><%= link_to 'Добавить блок приёмов',:controller => "visits", :action => "new_block" %></button>
<button><%= link_to 'Посмотреть все приёмы', visits_path %></button>
<button onclick="window.location.href = '/users';">Посмотреть всех пользователей</button>
<%end%>     
</div>

app/views/main/view_all.html.erb
<h2 id="data"><%= t('.data') %> <%=@date %></h2>

<% if @act == 'find_pat' && @current_user.role == "doctor" %>
  <div class="alert_alert-success" role="alert">
  <%= form_tag  url_for(controller: :main, action: :analyze), method: 'get', remote: true, class: 'alert_alert-success', id: 'analyze' do %>
    Выберите количество дней для формирования отчёта
    <input type="number" name="number_days" id="number_days" step="1" min="1" max="100"/>
    <%= submit_tag("Получить отчёт") %>
    <% end %>
  </div>
  <div class="alert_alert-success" role="alert" id="analyze_result">
  </div>
  <%= line_chart [data: @data_chart_temp], min: 35, max: 40, id: 'chart_temp', title: "Температура (С)"%>
  <%= line_chart [data: @data_chart_h_pres], min: 60, max: 160, id: 'chart_h_pres', title: "Систолическое АД (мм.рт.ст.)"%>
  <%= line_chart [data: @data_chart_l_pres], min: 30, max: 100, id: 'chart_l_pres', title: "Диастолическое АД (мм.рт.ст.)"%>
  <%= line_chart [data: @data_chart_pulse], min: 40, max: 150, id: 'chart_pulse', title: "ЧСС (уд/мин)"%>
  <%= line_chart [data: @data_chart_satur], min: 80, max: 100, id: 'chart_satur', title: "Сатурация (%)"%>
<%end%>

<table>
  <thead>
    <tr>
      <th><%= t('.username') %> </th>
      <th><%= t('.date') %> </th>
      <th><%= t('.temp') %> </th>
      <th><%= t('.h_pres') %></th>
      <th><%= t('.l_pres') %></th>
      <th>ЧСС</th>
      <th>Сатурация</th>
      <th>Комментарий</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data.each do |datum| %>
      <tr>
        <td><%= datum.username %></td>
        <td id="date"><%= datum.data.strftime("%d-%m-%Y %H:%M") %></td>
        <td><%= datum.temp %></td>
        <td><%= datum.h_pres %></td>
        <td><%= datum.l_pres %></td>
        <td><%= datum.pulse %></td>
        <td><%= datum.satur %></td>
        <td><%= datum.comment %></td>
        <% if @current_user.username==datum.username %><td><button><%= link_to 'Редактировать', edit_datum_path(datum) %></button></td>
        <td><button><%= link_to 'Удалить', datum, method: :delete, data: { confirm: 'Вы уверены, что хотите удалить эту запись?' } %></button></td> <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button><%= link_to t('.back'), main_select_path %></button>

app/views/main/view_vis.html.erb
<h2 id="data"> Приёмы пациента: <%=@date %></h2>

<div class="alert_alert-success" role="alert">
  <%= form_tag  url_for(controller: :main, action: :filter), method: 'get', class: 'alert_alert-success', remote: true, id: 'filter_visits' do %>
    <b>Фильтры </b><br>
    Период с <input type="date" name="filter_date_from" id="filter_date_from"/> по 
    <input type="date" name="filter_date_to" id="filter_date_to" /><br>
    Врач <select name="doctor" id="filter_doctor">
      <option value="-">Все</option>
      <%=User.all.select{|user| user.role=="doctor"}.each do |doctor|%>
      <option value=<%=doctor.username%>><%=doctor.surname%> <%=doctor.name%> <%=doctor.patr%></option>
      <%end%>
    </select><br>
    <%= submit_tag("Применить") %>
    <% end %>
  </div>
<table>
  <thead>
    <tr>
      <th>Врач</th>
      <%if @current_user.role=="doctor"%>
      
      <%end%>
      <th><%= t('.date') %> </th>
      <% if @act1=="view_last" %>
      <th>Диагноз </th>
      <th><%= t('.compl') %> </th>
      <th>Анамнез</th>
      <th><%= t('.res') %></th>
      <th><%= t('.recom') %></th>
      <th>Рекомендованная дата для визита</th>
      <%end%>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="table">
    <% @data.each do |datum| %>
      <tr>
        <td id="doctor" class="doctor"><%= User.find_by_username(datum.doctor).surname %> <%= User.find_by_username(datum.doctor).name%> <%= User.find_by_username(datum.doctor).patr %></td>
        <%if @current_user.role=="doctor"%>
        
        <%end%>
        <td id="date" class="date"><%= datum.date.strftime("%d-%m-%Y %H:%M") %></td>
        <% if @act1=="view_last" %>
        <td><%= datum.diagnosis %></td>
        <td><%= datum.compl %></td>
        <td><%= datum.anamnesis %></td>
        <td><%= datum.res %></td>
        <td><%= datum.recom %></td>
        <td><%= datum.next_v%></td>
        <%end%>
        <% if @act1=="view_fut" %>
        <td><%= link_to 'Отменить', datum, method: :delete, data: { confirm: "Вы уверены что хотите отменить запись?"} %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('.back'), main_select_path %>