config/routes.rb
Rails.application.routes.draw do
  resources :visits
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'session#login'
    get 'session/login'
    post 'session/create'
    get 'session/logout'
    get 'users/new_doctor'
    post 'users/create_doctor'
    resources :users
    resources :data
    resources :visit
    get 'visits/new_block'
    post 'visits/create_block'
    get 'visits/filter'
    get 'main/select'
    get 'main/analyze'
    get 'main/filter'
    get 'main/view_all'
    get 'main/view_date'
    get 'main/view_vis'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/visit.rb
class Visit < ApplicationRecord
    validates :date, presence: true, uniqueness: true
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: %i[ show edit update destroy ]
  before_action :check_login, only: %i[index show new edit create update destroy new_block create_block]
  AdminID = 'admin'
  DoctorID = "doctor"
  # GET /visits or /visits.json
  def index
    if current_user.role!=DoctorID && current_user.username!=AdminID
      @doctors=User.all.select { |record| record.role == "doctor"}.sort_by(&:surname)
    @visits = Visit.all.select do |record|
                record.doctor!="" && record.user== ""  && record.date >= Time.now
              end.sort_by(&:date)
    elsif current_user.role==DoctorID
      @visits = Visit.all.select do |record|
        record.user!= "" && record.date >= Time.now && record.doctor == current_user.username
      end.sort_by(&:date)
    elsif current_user.username==AdminID
      @visits = Visit.all.select do |record|
        record.date >= Time.now
      end.sort_by(&:date)  
    end
  end

  # GET /visits/1 or /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit
  end

    # POST /visits or /visits.json
    def create
      @visit = Visit.new(visit_params)
  
      respond_to do |format|
        if @visit.save
          format.html { redirect_to visit_url(@visit), notice: "Приём успешно создан." }
          format.json { render :show, status: :created, location: @visit }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @visit.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def new_block
      
    end

    def create_block
      @date=params[:date]
      @doctor=params[:doctor]
      @time_start=DateTime.parse(params[:time_start])
      @time_end=DateTime.parse(params[:time_end])
      @duration=params[:duration]
        cnt=0
        p @time_start
      while (@time_start<@time_end && cnt<=5)
        p @time_start
        @visit = Visit.new
        @visit.date=@time_start
        @visit.doctor=@doctor
        @visit.user=''
        if !@visit.save
          @notice="Ошибка добавления записей"
          #redirect_to visits_new_block_path, notice:"Ошибка добавления записей"
          #return
        else 
          @notice="Записи успешно добавлены"
        end
        cnt=cnt+1
        @time_start=Time.at(@time_start.to_i+@duration.to_i*60)
        p @time_start
      end
      render json:{notice:@notice}
      #redirect_to visits_new_block_path
    end  

  # PATCH/PUT /visits/1 or /visits/1.json
  def update
    if @current_user.role!=DoctorID
    respond_to do |format|
      if @visit.update(user: @current_user.username)
          format.html { redirect_to visit_url(@visit), notice: "Вы успешно записались на приём." }
          p "add"
          format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
    end
    if @current_user.role==DoctorID
      respond_to do |format|
        if @visit.update(visit_params)
          format.html { redirect_to visit_path(@visit) , notice: "Данные сохранены"}
            p "add"
          format.json { render :show, status: :ok, location: @visit }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @visit.errors, status: :unprocessable_entity }
        end
      end
    end
  end


  def filter
    render json: { data: @data}
  end
  # DELETE /visits/1 or /visits/1.json
  def destroy
    if current_user.role!=DoctorID && current_user.username!=AdminID
    @visit.update(user: "")

    respond_to do |format|
      format.html { redirect_to main_select_path }
      format.json { head :no_content }
    end
  end
  if current_user.username==AdminID
    @visit.destroy

    respond_to do |format|
      format.html { redirect_to visits_path }
      format.json { head :no_content }
    end
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def visit_params
      params.require(:visit).permit(:date, :user, :compl, :res, :recom, :next_v, :doctor, :anamnesis, :diagnosis)
    end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_with(model: visit, local: true) do |form| %>
  <% if visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% visit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Дата и время" %>
    <%= form.datetime_local_field :date , disabled:"disabled"%>
  </div>

  <div class="field">
  <%= form.label "Доктор" %>
  <%= form.text_field :doctor , disabled:"disabled"%>
  </div>

  <div class="field">
    <%= form.label "Пациент" %>
    <%= form.text_field :user , disabled:"disabled"%>
  </div>

  <div class="field">
    <%= form.label "Диагноз" %>
    <%= form.text_area :diagnosis, style:"width:600px; height:70px;"%>
  </div>
  
  <div class="field">
  <%= form.label "Анамнез" %>
  <%= form.text_area :anamnesis, style:"width:600px; height:70px;" %>
  </div>

  <div class="field">
    <%= form.label "Жалобы" %>
    <%= form.text_area :compl, style:"width:600px; height:70px;" %>
  </div>

  <div class="field">
    <%= form.label "Результаты осмотра" %>
    <%= form.text_area :res, style:"width:600px; height:70px;"%>
  </div>

  <div class="field">
    <%= form.label "Рекомендации" %>
    <%= form.text_area :recom, style:"width:600px; height:70px;" %>
  </div>

  <div class="field">
    <%= form.label "Следующий визит" %>
    <%= form.datetime_local_field :next_v %>
  </div>
  <div class="actions">
    <%= form.submit  "Сохранить изменения"%>
  </div>
<% end %>

app/views/visits/_form1.html.erb
<%= form_with(model: visit, local: true) do |form| %>
    <% if visit.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(visit.errors.count, "error") %> prohibited this visit from being saved:</h2>
  
        <ul>
        <% visit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <p>
  <strong>Дата и время:</strong>
  <%= @visit.date.strftime("%d-%m-%Y %H:%M") %>
    </p>
    <p>
  <strong>Врач:</strong>
  <%= User.find_by_username(@visit.doctor).surname %> <%= User.find_by_username(@visit.doctor).name %> <%= User.find_by_username(@visit.doctor).patr %>
    </p>
  
    <div class="actions">
      <%= form.submit value="Записаться" %>
    </div>
  <% end %>

app/views/visits/edit.html.erb
<h1></h1>

<%if current_user.role!="doctor"%>
<h1>Запись на приём</h1>
<%= render 'form1', visit: @visit %>
<%else%>
<h1>Протокол приёма</h1>
 <h2><%= User.find_by_username(@visit.user).surname %> <%= User.find_by_username(@visit.user).name%> <%= User.find_by_username(@visit.user).patr %></td>
</h2>
<p><button><%= link_to 'Перейти к дневнику здоровья пациента', :controller=>"main", :action=>"view_all",
:surname=> User.find_by_username(@visit.user).surname,:name=> User.find_by_username(@visit.user).name,
:patr=> User.find_by_username(@visit.user).patr,
:act=> "find_pat"%></button> <button><%= link_to 'Перейти к истории приёмов пациента', :controller=>"main", :action=>"view_vis",
:surname=> User.find_by_username(@visit.user).surname,:name=> User.find_by_username(@visit.user).name,
:patr=> User.find_by_username(@visit.user).patr,
:act1=> "view_last"%></button></p>
<%= render 'form', visit: @visit %>
<%end%>

app/views/visits/index.html.erb
<p id="notice"><%= notice %></p>
<% if @current_user.role!="doctor" && @current_user.username!="admin"%>
<h2>Запись на приём</h2>
<%end%>
<% if @current_user.username=="admin" %>
<div class="alert_alert-success" role="alert">
  <%= form_tag  url_for(controller: :visits, action: :filter), method: 'get', class: 'alert_alert-success', remote: true, id: 'filter_visits' do %>
    Фильтры <br>
    Период с <input type="date" name="filter_date_from" id="filter_date_from"/> по 
    <input type="date" name="filter_date_to" id="filter_date_to" /><br>
    Врач <select name="doctor" id="filter_doctor">
      <option value="-">Все</option>
      <%=User.all.select{|user| user.role=="doctor"}.each do |doctor|%>
      <option value=<%=doctor.username%>><%=doctor.surname%> <%=doctor.name%> <%=doctor.patr%></option>
      <%end%>
    </select><br>
    <%= submit_tag("Применить") %>
    <% end %>
  </div>
<%end%>

<table>
  <thead>
    <tr>
    <% if @current_user.role!="doctor" %>
      <th>Врач</th>
      <% end%>
      <% if @current_user.role=="doctor" %>
      <th>Пациент</th>
      <% end%>
      <% if @current_user.role!="doctor" &&  @current_user.username!="admin"%>
      <%prev_date=0%>
      <% @visits.sort_by(&:date).each do |visit| %>
        <% if visit.date.to_date > prev_date %>
      <th><%= visit.date.strftime("%d-%m-%Y") %></th>
      <% end %>
      <%prev_date = visit.date.to_date%> <%p visit.date%>
      <%end%>
      <% end%>
      <th colspan="5"></th>
    </tr>
  </thead>

  <% if (@current_user.role!="doctor" && @current_user.username!="admin")%>
  <tbody>
  <% @doctors.each do |doctor| %>
    <tr>
      <td><%= doctor.surname%> <%= doctor.name%> <%= doctor.patr %></td>
      <%prev_date = 0 %>
      <% @visits.select{ |visit| visit.doctor == doctor.username}.sort_by(&:date).each do |visit| %>
      <% if visit.date.to_date > prev_date %>
      </td><td><button><%= link_to visit.date.strftime("%d-%m-%Y %H:%M"), edit_visit_path(visit) %></button>
      <% else %> <br><button><%= link_to visit.date.strftime("%d-%m-%Y %H:%M"), edit_visit_path(visit) %></button>
      <% end %>
      <%prev_date = visit.date.to_date%> <%p visit.date%>
      <%end%>
    </tr>
  <% end %>
  <% end %>


<% if @current_user.role=="doctor" %>
    <% @visits.each do |visit| %>
      <tr>
      <td><%= User.find_by_username(visit.user).surname%> <%= User.find_by_username(visit.user).name%> <%= User.find_by_username(visit.user).patr%></td>
        <td><%= visit.date.strftime("%Y-%m-%d %H:%M") %></td>
        <td><%= link_to 'Начать приём', edit_visit_path(visit) %></td>
      </tr>
    <% end %>
    <% end %>


    <% if @current_user.username=="admin" %>
    <% @visits.each do |visit| %>
      <tr>
        <td id="doctor" class="doctor"><%= User.find_by_username(visit.doctor).surname %> <%= User.find_by_username(visit.doctor).name%> <%= User.find_by_username(visit.doctor).patr %></td>
        <td id="date" class="date"><%= visit.date.strftime("%d-%m-%Y %H:%M") %></td>
        <td><%= link_to "Удалить", visit, method: :delete, data: { confirm: "Удалить приём?" } %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>

app/views/visits/new.html.erb
<h1>Новый приём</h1>

<%= render 'form', visit: @visit %>

app/views/visits/new_block.html.erb
<h2>Добавление блока приёмов врача</h2>
<p class='alert alert_success' role="alert" id="notice" ></p>
<div class="error" ><%= @notice %></div>
<div class="alert_alert-success" role="alert">
  <%= form_tag  url_for(controller: :visits, action: :create_block), method: 'post', class: 'alert_alert-success', id:'create_block', remote: 'true' do %>
    <strong>Выберите параметры для добавления приёмов врача</strong><br>
    Врач <select name="doctor" id="doctor">
      <%=User.all.select{|user| user.role=="doctor"}.each do |doctor|%>
      <option value=<%=doctor.username%>><%=doctor.surname%> <%=doctor.name%> <%=doctor.patr%></option>
      <%end%>
    </select><br>
    Начало приёмного времени <input type="datetime-local" name="time_start" id="time_start"/><br>
    Окончания приёмного времени <input type="datetime-local" name="time_end" id="time_end"/><br>
    Продолжительность приёма пациента <input type="number" name="duration" id="duration" min="1"/> мин<br>
    <%= submit_tag("Добавить приёмы") %>
    <% end %>
  </div>

app/views/visits/show.html.erb
</br><p id="notice"><%= notice %></p>

<p>
  <strong>Дата:</strong>
  <%= @visit.date.strftime("%d-%m-%Y %H:%M") %>
</p>

<p>
  <strong>Пациент:</strong>
  <%= User.find_by_username(@visit.user).surname%> <%= User.find_by_username(@visit.user).name%> <%= User.find_by_username(@visit.user).patr%> 
</p>

<p>
  <strong>Врач:</strong>
  <%= User.find_by_username(@visit.doctor).surname%> <%= User.find_by_username(@visit.doctor).name%> <%= User.find_by_username(@visit.doctor).patr%>  
</p>
<% if @current_user.role!="doctor" %>
<button><%= link_to 'Добавить запись на приём', main_select_path %></button>
<%end%>
<% if @current_user.role=="doctor" %>

<p>
  <strong>Диагноз:</strong>
  <%= @visit.diagnosis %>
</p>

<p>
  <strong>Анамнез:</strong>
  <%= @visit.anamnesis %>
</p>

<p>
  <strong>Жалобы:</strong>
  <%= @visit.compl %>
</p>

<p>
  <strong>Результаты осмотра:</strong>
  <%= @visit.res %>
</p>

<p>
  <strong>Рекомендации:</strong>
  <%= @visit.recom %>
</p>

<p>
  <strong>Дата следующего визита:</strong>
  <%= @visit.next_v %>
</p>
<button><%= link_to 'Редактировать', edit_visit_path(@visit) %> </button>
<button><%= link_to 'Перейти к списку приёмов', main_select_path %></button>
<%end%>