config/routes.rb
Rails.application.routes.draw do
  resources :visits
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'session#login'
    get 'session/login'
    post 'session/create'
    get 'session/logout'
    get 'users/new_doctor'
    post 'users/create_doctor'
    resources :users
    resources :data
    resources :visit
    get 'visits/new_block'
    post 'visits/create_block'
    get 'visits/filter'
    get 'main/select'
    get 'main/analyze'
    get 'main/filter'
    get 'main/view_all'
    get 'main/view_date'
    get 'main/view_vis'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/session_controller.rb
# frozen_string_literal: true

class SessionController < ApplicationController
  skip_before_action :check_login, only: %i[login create]

  def login; end

  def create
    user = User.find_by(username: params[:username])

    if user&.authenticate(params[:password])
      p 'login'
      sign_in user
      redirect_to main_select_path
    else
      p 'incorrect username or password'
      redirect_to session_login_path, notice: t('session.login.user_not_found')
    end
  end

  def logout
    sign_out
    redirect_to root_path
  end
end

app/helpers/session_helper.rb
module SessionHelper
  def sign_in(user)
    cookies.signed[:user_id] = { value: user.id, expires: 20.days, httponly: true }
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.signed[:user_id] = nil
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by(id: cookies.signed[:user_id])
  end
end

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/login.html.erb
<div class="center jumbotron">
<h2><%= t('.log_in') %></h2>


<div class="error" ><%= notice %></div>
<div>
<%= form_with url: session_create_url, method: :post, local: true do |f| %>
    <h><%= t('.username') %> </h><%= f.text_field :username, required: true%>
    <h><%= t('.password') %> </h><%= f.password_field :password, required: true%>
    <h><%= f.submit t('.enter') %></h>
<% end %>

<%= link_to t('.sign_up'), new_user_path %>
</div>
</div>

app/views/session/logout.html.erb
<h1>Session#logout</h1>
<p>Find me in app/views/session/logout.html.erb</p>