config/routes.rb
Rails.application.routes.draw do
  resources :visits
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'session#login'
    get 'session/login'
    post 'session/create'
    get 'session/logout'
    get 'users/new_doctor'
    post 'users/create_doctor'
    resources :users
    resources :data
    resources :visit
    get 'visits/new_block'
    post 'visits/create_block'
    get 'visits/filter'
    get 'main/select'
    get 'main/analyze'
    get 'main/filter'
    get 'main/view_all'
    get 'main/view_date'
    get 'main/view_vis'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalWork</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav>
          <h class="navbar-brand"><%=t('.medic')%></h>
          <ul class="nav navbar-nav navbar-right">
          <% if @current_user!=nil%>
            <li class="navbar-brand"><svg xmlns="http://www.w3.org/2000/svg"  width="30" height="25" fill="currentColor" color="#FFFFFF" class="bi bi-person-circle" viewBox="0 0 16 16">
            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
             <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
        </svg></li>
            <li ><%= link_to @current_user.username, edit_user_path(@current_user) %></li><%end%>
            <li><%= link_to t('.home'),   main_select_path %></li>
            <li><%= link_to t('.exit'), session_logout_path %></li>
          </ul>
        </nav>
      </div>
    </header>
    <pre>
    </pre>
    <div class="container" style="width:90%">
      <%= yield %>
    </div>
  </body>
</html>